[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["...", "python311", "openssl"]
aptPkgs = ["...", "openssh-client", "build-essential", "libssl3", "libssl-dev", "openssl"]

[phases.install]
cmds = [
  "bun install",
  "ln -s /usr/lib/*/libssl.so.3 /usr/lib/libssl.so.3 || true", 
  "ln -s /usr/lib/*/libcrypto.so.3 /usr/lib/libcrypto.so.3 || true",  
]

[start]
cmd = "bun apply-migrations-if-needed && bun start"